
---
- hosts: slave
  become: true
  become_method: sudo 
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install prerequisites
      become: true
      become_user: root
      become_method: sudo 
      apt:
       name: "{{ item }}"
       state: latest
       update_cache: yes
      with_items:  
       - 'aptitude'
       - 'vim' 

  #Apache Configuration
    - name: Install LAMP Package s
      become: true
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]

    - name: Create document root
      file:
        path: "/var/www/html"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Set up Apache virtualhost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

  # MySQL Configuration
  #- name: Sets the root password
  #   mysql_user:
  #     name: root
  #     password: "{{ mysql_root_password }}"
  #     login_unix_socket: /var/run/mysqld/mysqld.sock
       

    - name: Removes all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Removes the MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name:  the MySQL test database
      mysql_db:
        name: cis_dev
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"


    - name: Copy DB
      shell: scp -P 22 /tmp/cis.sql ubuntu@{{ ansible_local_host }}:/tmp/cis.sql
      become: false
        

    - name: "Import cis db"
      mysql_db:
        state: import
        name: cis
        encoding: utf8
        target: /tmp/cis.sql
        login_user: root
        login_password: "{{ mysql_root_password }}"

  # UFW Configuration
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  # PHP Info Page
    - name: Sets Up PHP Info Page
      template:
        src: "files/info.php.j2"
        dest: "/var/www/html/info.php"

    - name: Copy GoodMorning App
      copy:
        directory_mode: yes
        src: "files/goodmorning/"
        remote_src: no
        dest: "/var/www/html/"
        mode: '0755'

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart apache
      service:
        name: apache2
        state: restarted
